name: Build and Release

on:
  push:
    tags:
      - v**

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      - id: set_tag
        run: echo "::set-output name=tag_name::${GITHUB_REF#refs/tags/}"
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.set_tag.outputs.tag_name }}
          release_name: ${{ steps.set_tag.outputs.tag_name }}
          draft: false
          prerelease: false
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: '@xenodrive'
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - run: pnpm i --frozen-lockfile --strict-peer-dependencies
      - run: pnpm dev:prepare
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
